### ISSUE TITLE
Gallery video compression issue

### ISSUE THREAD

**Issue by DroidVent** [chenzhihui28/VideoRecorderAndCompressor#11]
I selected a gallery video(not camera captured). Original file size was 3.77 MB but after compression it changed to 17 MB. Please let me know what is issue. Thankss

**Comment by chenzhihui28** [comment]
I have not encountered this problem. I think the problem is that the original video's resolution is lower than the target resolution of the compress command configure. The meaning of the default command is to compress the original video to 640x480 (16:9), so you can check you original video file's resolution to see if it's lower than 640x480, if is lower, you can modify the command and make sure the resolution is lower than your original video's. If there is any progress, please let me know, thanks.
